#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# Compute Docker resource limits for the ERPNext stack from host capacity,
# using the balanced percentage allocation documented in README.md.
#
# Why percentage-based: a fixed 3 GB cap on `backend` is fine on a 16 GB
# host and crippling on a 64 GB host. Scaling proportionally keeps the
# same headroom ratio at any size.
#
# Usage:
#   ./scripts/tune-resources.sh                  # auto-detect host
#   ./scripts/tune-resources.sh 32 8             # 32 GB RAM, 8 vCPU
#   ./scripts/tune-resources.sh >> .env          # append to .env
#
# Then run: ./upgrade.sh   (or, for first boot, docker compose up -d)
# ---------------------------------------------------------------------------

set -euo pipefail

# --- Allocation policy --------------------------------------------------------
# Memory: 85% of host memory is divided across services. The remaining 15%
# covers kernel buffers, the host-side reverse proxy, the Docker daemon, and
# burst capacity for whichever service is briefly over its reservation.
#
# CPU: limits intentionally overcommit (sum > 100% of host CPU). CPU is a
# soft constraint — overrun causes throttling, never OOM kills — and in
# practice only one or two services are CPU-bound at a time.
# -----------------------------------------------------------------------------

ALLOC_PCT_OF_HOST_MEM=85       # remainder reserved for OS + headroom

# Memory share within the allocatable pool (must sum to 100)
MEM_PCT_DB=30                  # MariaDB InnoDB buffer pool
MEM_PCT_BACKEND=18             # gunicorn web workers
MEM_PCT_QUEUE_LONG=22          # DMS OCR + LibreOffice + heavy reports
MEM_PCT_QUEUE_SHORT=8          # interactive background jobs
MEM_PCT_REDIS_CACHE=5          # Frappe doctype/document cache
MEM_PCT_REDIS_QUEUE=5          # RQ broker + socketio pubsub
MEM_PCT_WEBSOCKET=4            # Node.js socketio
MEM_PCT_SCHEDULER=4            # cron-like job emitter
MEM_PCT_FRONTEND=4             # internal nginx (static + proxy)
# sum = 100

# CPU share (fraction of host CPU; sums to >100% on purpose)
CPU_PCT_DB=50
CPU_PCT_BACKEND=50
CPU_PCT_QUEUE_LONG=50
CPU_PCT_QUEUE_SHORT=25
CPU_PCT_REDIS_CACHE=10
CPU_PCT_REDIS_QUEUE=10
CPU_PCT_WEBSOCKET=15
CPU_PCT_SCHEDULER=15
CPU_PCT_FRONTEND=25

# --- Host capacity detection --------------------------------------------------
if [ $# -ge 2 ]; then
  HOST_MEM_GB="$1"
  HOST_CPU="$2"
else
  if command -v nproc >/dev/null 2>&1; then
    HOST_CPU="$(nproc)"
  elif command -v sysctl >/dev/null 2>&1; then
    HOST_CPU="$(sysctl -n hw.ncpu)"
  else
    HOST_CPU=4
  fi

  if [ -r /proc/meminfo ]; then
    HOST_MEM_KB="$(awk '/^MemTotal:/ {print $2}' /proc/meminfo)"
    HOST_MEM_GB=$(( (HOST_MEM_KB + 524288) / 1024 / 1024 ))   # round to nearest GB
  elif command -v sysctl >/dev/null 2>&1; then
    HOST_MEM_BYTES="$(sysctl -n hw.memsize)"
    HOST_MEM_GB=$(( HOST_MEM_BYTES / 1024 / 1024 / 1024 ))
  else
    echo "ERROR: cannot detect host memory; pass it: $0 <GB> <vCPU>" >&2
    exit 1
  fi
fi

# --- Sanity --------------------------------------------------------------------
if [ "${HOST_MEM_GB}" -lt 6 ]; then
  cat >&2 <<EOF
ERROR: Host has only ${HOST_MEM_GB} GB RAM. This stack will not run reliably
       under 8 GB. MariaDB + Frappe workers + DMS OCR together need real
       memory. Add more RAM or move the DB to a separate host.
EOF
  exit 1
fi

if [ "${HOST_MEM_GB}" -lt 8 ]; then
  echo "WARNING: ${HOST_MEM_GB} GB is the bare minimum. Expect tight headroom." >&2
fi

if [ "${HOST_CPU}" -lt 2 ]; then
  echo "ERROR: Need at least 2 vCPU. Detected ${HOST_CPU}." >&2
  exit 1
fi

ALLOC_MB=$(( HOST_MEM_GB * 1024 * ALLOC_PCT_OF_HOST_MEM / 100 ))

# --- Helpers ------------------------------------------------------------------
# Output a CPU value with 1 decimal place. Floor at 0.25 so no service is
# starved to the point Compose refuses to start it.
cpu_share() {
  local pct=$1
  local hundredths=$(( HOST_CPU * pct ))      # = HOST_CPU * (pct/100) * 100
  # Floor at 0.3 vCPU so even the lightest service isn't starved on
  # small hosts. (Redis is I/O-bound; 0.3 is plenty.)
  if [ "${hundredths}" -lt 30 ]; then
    hundredths=30
  fi
  local int=$(( hundredths / 100 ))
  local frac=$(( (hundredths % 100) / 10 ))
  echo "${int}.${frac}"
}

mem_share() {
  local pct=$1
  local mb=$(( ALLOC_MB * pct / 100 ))
  # Floor at 128 MB so even tiny services don't get a value the kernel
  # refuses (cgroup minimum is small but Compose may misbehave below ~64 MB).
  if [ "${mb}" -lt 128 ]; then
    mb=128
  fi
  echo "${mb}m"
}

# --- Output -------------------------------------------------------------------
cat <<EOF
# -----------------------------------------------------------------------------
# Tuned for host: ${HOST_MEM_GB} GB RAM / ${HOST_CPU} vCPU
# Allocatable pool: $(( ALLOC_MB / 1024 )) GB (${ALLOC_PCT_OF_HOST_MEM}% of host)
# Generated by scripts/tune-resources.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Adjust any single value below by hand if you have asymmetric needs
# (e.g. heavy DMS OCR pipeline -> bump QUEUE_LONG_MEM_LIMIT).
# -----------------------------------------------------------------------------

DB_MEM_LIMIT=$(mem_share $MEM_PCT_DB)
DB_CPU_LIMIT=$(cpu_share $CPU_PCT_DB)

BACKEND_MEM_LIMIT=$(mem_share $MEM_PCT_BACKEND)
BACKEND_CPU_LIMIT=$(cpu_share $CPU_PCT_BACKEND)

QUEUE_LONG_MEM_LIMIT=$(mem_share $MEM_PCT_QUEUE_LONG)
QUEUE_LONG_CPU_LIMIT=$(cpu_share $CPU_PCT_QUEUE_LONG)

QUEUE_SHORT_MEM_LIMIT=$(mem_share $MEM_PCT_QUEUE_SHORT)
QUEUE_SHORT_CPU_LIMIT=$(cpu_share $CPU_PCT_QUEUE_SHORT)

REDIS_CACHE_MEM_LIMIT=$(mem_share $MEM_PCT_REDIS_CACHE)
REDIS_CACHE_CPU_LIMIT=$(cpu_share $CPU_PCT_REDIS_CACHE)

REDIS_QUEUE_MEM_LIMIT=$(mem_share $MEM_PCT_REDIS_QUEUE)
REDIS_QUEUE_CPU_LIMIT=$(cpu_share $CPU_PCT_REDIS_QUEUE)

WEBSOCKET_MEM_LIMIT=$(mem_share $MEM_PCT_WEBSOCKET)
WEBSOCKET_CPU_LIMIT=$(cpu_share $CPU_PCT_WEBSOCKET)

SCHEDULER_MEM_LIMIT=$(mem_share $MEM_PCT_SCHEDULER)
SCHEDULER_CPU_LIMIT=$(cpu_share $CPU_PCT_SCHEDULER)

FRONTEND_MEM_LIMIT=$(mem_share $MEM_PCT_FRONTEND)
FRONTEND_CPU_LIMIT=$(cpu_share $CPU_PCT_FRONTEND)
EOF
